/* tipos*/
INSERT INTO tipo VALUES(1,'normal');
INSERT INTO tipo VALUES(2,'fighting');
INSERT INTO tipo VALUES(3,'flying');
INSERT INTO tipo VALUES(4,'poison');
INSERT INTO tipo VALUES(5,'ground');
INSERT INTO tipo VALUES(6,'rock');
INSERT INTO tipo VALUES(7,'bug');
INSERT INTO tipo VALUES(8,'ghost');
INSERT INTO tipo VALUES(9,'steel');
INSERT INTO tipo VALUES(10,'fire');
INSERT INTO tipo VALUES(11,'water');
INSERT INTO tipo VALUES(12,'grass');
INSERT INTO tipo VALUES(13,'electric');
INSERT INTO tipo VALUES(14,'psychic');
INSERT INTO tipo VALUES(15,'ice');
INSERT INTO tipo VALUES(16,'dragon');
INSERT INTO tipo VALUES(17,'dark');
INSERT INTO tipo VALUES(18,'fairy');
INSERT INTO tipo VALUES(19,'unkown');
INSERT INTO tipo VALUES(20,'shadow');

/*habilidad*/
INSERT INTO habilidad VALUES(1,'overgrow');
INSERT INTO habilidad VALUES(2,'blaze');
INSERT INTO habilidad VALUES(3,'torrent');
INSERT INTO habilidad VALUES(4,'shield-dust');
INSERT INTO habilidad VALUES(5,'shed-skin');
INSERT INTO habilidad VALUES(6,'compound-eyes');
INSERT INTO habilidad VALUES(7,'swarm');
INSERT INTO habilidad VALUES(8,'keen-eye');
INSERT INTO habilidad VALUES(9,'tangled-feet');
INSERT INTO habilidad VALUES(10,'run-away');
INSERT INTO habilidad VALUES(11,'static');

/*pokemon*/

INSERT INTO pokemon VALUES (1,'bulbasaur', 'There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger', 0.7,6.9,true,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1.png');
INSERT INTO pokemon VALUES (2, 'ivysaur', 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs', 1,13,true,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/2.png');
INSERT INTO pokemon VALUES (3, 'venusaur', 'Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight', 2,100,false,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/3.png');
INSERT INTO pokemon VALUES (4, 'chamander','It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail',0.6,8.5,true,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/4.png');
INSERT INTO pokemon VALUES (5, 'charmeleon','It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws' ,1.1, 19,true,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/5.png');
INSERT INTO pokemon VALUES (6,'charizard', 'It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames' ,1.7,90.5,false,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/6.png');
INSERT INTO pokemon VALUES (7, 'squirtle', 'When it retracts its long neck into its shell, it squirts out water with vigorous force', 0.5, 9,true,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/7.png');
INSERT INTO pokemon VALUES (8,'wartortle','It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old', 1, 22.5,true,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/8.png');
INSERT INTO pokemon VALUES (9,'blastoise','It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell', 1.6,85.5,false,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/9.png');
INSERT INTO pokemon VALUES (10,'caterpie','For protection, it releases a horrible stench from the antenna on its head to drive away enemies',0.3,2.9,true,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/10.png');
INSERT INTO pokemon VALUES (11, 'metapod','It is waiting for the moment to evolve. At this stage, it can only harden, so it remains motionless to avoid attack',0.7,9.9,true,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/11.png');
INSERT INTO pokemon VALUES (12,'butterfree','In battle, it flaps its wings at great speed to release highly toxic dust into the air',1.1,32,false,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/12.png');
INSERT INTO pokemon VALUES(13,'weedle','Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves',0.3,3.2,true,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/13.png');
INSERT INTO pokemon VALUES(14,'kakuna', 'Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy',0.6,10,true,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/14.png');
INSERT INTO pokemon VALUES(15,'beedrill','It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly',1,29.5,false,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/15.png');
INSERT INTO pokemon VALUES(16,'pidgey','Very docile. If attacked, it will often kick up sand to protect itself rather than fight back',0.3,1.8,true,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/16.png');
INSERT INTO pokemon VALUES(17,'pidgeotto','This Pokémon is full of vitality. It constantly flies around its large territory in search of prey',1.1,30,true,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/17.png');
INSERT INTO pokemon VALUES(18,'pidgeot','This Pokémon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons',1.5,39.5,false,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/18.png');
INSERT INTO pokemon VALUES(19,'rattata','Will chew on anything with its fangs. If you see one, you can be certain that 40 more live in the area', 0.3,3.5,true,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/19.png');
INSERT INTO pokemon VALUES(20,'raticate','Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey',0.7,18.5,false,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/20.png');
INSERT INTO pokemon VALUES(25,'pikachu','Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy',0.4,6,true,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/25.png');
INSERT INTO pokemon VALUES(26,'raichu','Its long tail serves as a ground to protect itself from its own high-voltage power',0.8,30,false,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/26.png');


/*tipo de pokemon*/
INSERT INTO tipo_pokemon VALUES(1,12);
INSERT INTO tipo_pokemon VALUES(1,4);
INSERT INTO tipo_pokemon VALUES(2,12);
INSERT INTO tipo_pokemon VALUES(2,4);
INSERT INTO tipo_pokemon VALUES(3,12);
INSERT INTO tipo_pokemon VALUES(3,4);
INSERT INTO tipo_pokemon VALUES(4,10);
INSERT INTO tipo_pokemon VALUES(5,10);
INSERT INTO tipo_pokemon VALUES(6,10);
INSERT INTO tipo_pokemon VALUES(6,3);
INSERT INTO tipo_pokemon VALUES(7,11);
INSERT INTO tipo_pokemon VALUES(8,11);
INSERT INTO tipo_pokemon VALUES(9,11);
INSERT INTO tipo_pokemon VALUES(10,7);
INSERT INTO tipo_pokemon VALUES(11,7);
INSERT INTO tipo_pokemon VALUES(12,7);
INSERT INTO tipo_pokemon VALUES(12,3);
INSERT INTO tipo_pokemon VALUES(13,4);
INSERT INTO tipo_pokemon VALUES(13,7);
INSERT INTO tipo_pokemon VALUES(14,4);
INSERT INTO tipo_pokemon VALUES(14,7);
INSERT INTO tipo_pokemon VALUES(15,4);
INSERT INTO tipo_pokemon VALUES(15,7);
INSERT INTO tipo_pokemon VALUES(16,1);
INSERT INTO tipo_pokemon VALUES(16,3);
INSERT INTO tipo_pokemon VALUES(17,1);
INSERT INTO tipo_pokemon VALUES(17,3);
INSERT INTO tipo_pokemon VALUES(18,1);
INSERT INTO tipo_pokemon VALUES(18,3);
INSERT INTO tipo_pokemon VALUES(19,1);
INSERT INTO tipo_pokemon VALUES(20,1);
INSERT INTO tipo_pokemon VALUES(25,13);
INSERT INTO tipo_pokemon VALUES(26,13);

/*habilidad de pokemon*/
INSERT INTO habilidad_pokemon VALUES(1,1);
INSERT INTO habilidad_pokemon VALUES(2,1);
INSERT INTO habilidad_pokemon VALUES(3,1);
INSERT INTO habilidad_pokemon VALUES(4,2);
INSERT INTO habilidad_pokemon VALUES(5,2);
INSERT INTO habilidad_pokemon VALUES(6,2);
INSERT INTO habilidad_pokemon VALUES(7,3);
INSERT INTO habilidad_pokemon VALUES(8,3);
INSERT INTO habilidad_pokemon VALUES(9,3);
INSERT INTO habilidad_pokemon VALUES(10,4);
INSERT INTO habilidad_pokemon VALUES(11,5);
INSERT INTO habilidad_pokemon VALUES(12,6);
INSERT INTO habilidad_pokemon VALUES(13,4);
INSERT INTO habilidad_pokemon VALUES(14,5);
INSERT INTO habilidad_pokemon VALUES(15,7);
INSERT INTO habilidad_pokemon VALUES(16,8);
INSERT INTO habilidad_pokemon VALUES(16,9);
INSERT INTO habilidad_pokemon VALUES(17,8);
INSERT INTO habilidad_pokemon VALUES(17,9);
INSERT INTO habilidad_pokemon VALUES(18,8);
INSERT INTO habilidad_pokemon VALUES(18,9);
INSERT INTO habilidad_pokemon VALUES(19,10);
INSERT INTO habilidad_pokemon VALUES(20,10);
INSERT INTO habilidad_pokemon VALUES(25,11);
INSERT INTO habilidad_pokemon VALUES(26,11);